version: "3.5"

services:
  ${DIR_PREFIX}-${NETWORK}-${SERVICE_VERSION}:
    container_name: ${DIR_PREFIX}-${NETWORK}-${SERVICE_VERSION}-container
    network_mode: "host"
    build:
      context: ./
      dockerfile: ${DOCKERFILE}
      args:
        CARDANO_NODE_VERSION: ${SERVICE_VERSION}
        DINGO_VERSION: ${SERVICE_VERSION}
        CARDANO_NETWORK: ${NETWORK}
        CARDANO_NODE_NETWORK_ID: ${NETWORK_ID}
        CARDANO_NODE_PORT: ${NODE_PORT}
    labels:
      - "managed-by=testnet-docker-node"
    restart: always
    volumes:
      - ./${DIR_PREFIX}-${NETWORK}-${SERVICE_VERSION}/db:/data/db
      - ./${DIR_PREFIX}-${NETWORK}-${SERVICE_VERSION}/config:/config
      - ./${DIR_PREFIX}-${NETWORK}-${SERVICE_VERSION}/ipc:/ipc
      - ./keys:/keys
      - ./txs:/txs
      - ./dumps:/dumps
      - ./utilities:/utilities
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
