version: "3.5"

services:
  cardano-node-${NETWORK}-${NODE_VERSION}:
    container_name: node-${NETWORK}-${NODE_VERSION}-container
    network_mode: "host"
    build:
      context: ./
      args:
        CARDANO_NODE_VERSION: ${NODE_VERSION}
        CARDANO_NODE_NETWORK_ID: ${NETWORK_ID}
        CARDANO_NODE_PORT: ${NODE_PORT}
    labels:
      - "managed-by=testnet-docker-node"
    restart: always
    volumes:
      - ./node-${NETWORK}-${NODE_VERSION}/db:/data/db
      - ./node-${NETWORK}-${NODE_VERSION}/config:/config
      - ./node-${NETWORK}-${NODE_VERSION}/ipc:/ipc
      - ./keys:/keys
      - ./txs:/txs
      - ./dumps:/dumps
      - ./utilities:/utilities
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-socat-${NETWORK}-${NODE_VERSION}:
    container_name: node-${NETWORK}-${NODE_VERSION}-socat
    image: alpine/socat
    ports:
      - "127.0.0.1:${SOCAT_PORT}:${SOCAT_PORT}"
    depends_on:
      - cardano-node-${NETWORK}-${NODE_VERSION}
    labels:
      - "managed-by=testnet-docker-node"
    volumes:
      - ./node-${NETWORK}-${NODE_VERSION}/ipc:/ipc
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "while [ ! -S /ipc/node.socket ]; do sleep 1; done; exec socat TCP-LISTEN:${SOCAT_PORT},fork,reuseaddr UNIX-CONNECT:/ipc/node.socket"
    restart: always

volumes:
  node-db:
  node-ipc:
